version: '3.8'
services:
  java_forest_db:
      container_name: java_forest_db
      restart: always
      image: postgres:13.1-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      volumes:
        - ./data:/var/lib/postgresql/data
  java_forest_react:
    container_name: java_forest_react
    image: forest-react-app:1.0.0
    build: ./front-forest
    ports:
      - 9000:9000
    depends_on:
      - java_forest_db
  java_forest_app:
    container_name: java_forest_app
    image: forest-java-app:1.0.0
    build: ./back-forest
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_forest_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - java_forest_react