#Docker compose version
version: '3.9'

#2 servicios se van a levantar 1 para la api y otro para la bd
services:
    java_forest_app:
      container_name: java_forest_app
      image: forest-java-app:1.0.0
      build: .
      ports:
        - 8080:8080
      environment:
        - DATABASE_PASSWORD=postgres
        - DATABASE_USERNAME=postgres
        - DATABASE_URL=jdbc:postgresql://java_forest_db:5432/postgres
      depends_on:
        - java_forest_db
    java_forest_db:
      container_name: java_forest_db
      image: postgres:12
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

